### ISSUE TITLE
Nuevos proyectos para piloto de extensión de bootcamp

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/bootcamp#1058]
Como parte del piloto de full stack, inicialmente diseñado como extensión de 3 meses a nuestro bootcamp de front-end, necesitamos diseñar entre 4 y 6 proyectos que cubran los objetivos de aprendizaje planteados en el brief (ver más abajo).

## Proyectos

Por ahora estamos trabajando en las siguientes propuestas de proyectos, y todavía abiertos a sugerencias nuevas. Me he tomado la libertad de crear un _issue_ por cada proyecto para hacer seguimiento por separado.

* [x] Roman numerals (lib / cli / slack slash command) - WIP :construction: #1057
* [x] WordPress custom site (blog, e-commerce) - WIP :construction: #1056
* [x] Chat app (real time, web sockets) - WIP :construction: #1055
* [ ] E-commerce (integración con PayPal, Stripe, Culqui, etc) - WIP :construction: #1054
* [x] Fleet Management Software WIP :construction: #1074 

***

## Objetivos de aprendizaje

Objetivos de aprendizaje en la extensión full-stack (lo que vendría después de terminar el bootcamp front-end):

### Node.js

* Uso de sistema de archivos.
* Instalar y usar módulos.
* Creación de módulos.
* Configuración de package.json
* Uso de npm scripts.
* Procesos (argv, env, stdin, stdout, stderr, etc)
* Closures
* Memory leaks

### Express

* Rutas
* Middleware

### Shell / UNIX

* processes
* users/permissions
* pipes
* redirection

### Bases de datos (SQL / NoSQL)

Para sus proyectos las estudiantes podrán elegir entre MongoDB, PostgreSQL o MySQL.

* Instalación
* Conexión a través de cliente
* Connection String
* Queries y comandos

### WebOps

* Integración continua
* Despliegue continuo

### Autenticación

* JWT
* passport
* Almacenamiento y acceso de contraseñas

### Contenedores

* docker
* docker-compose

### Protocolos de red

* HTTP
* REST
* GraphQL
* WebSockets
* UNIX Sockets

### Lenguajes de programación

Dado que las estudiantes de la extensión full-stack ya han pasado por el Bootcamp de Front-end de Laboratoria, ya tienen familiaridad con JavaScript, HTML y CSS. En la extensión la idea es que puedan continuar con JavaScript / Node.js o elegir un segundo lenguaje en el que iniciarse. Por ahora, como alternativas a JavaScript se plantea PHP/WordPress.

### Administración de sistemas

* Paquetes y administración de paquetes
* Procesos (daemons)
* Logs
* Puertos y firewalls
* Usuarios y permisos
* Copia de respaldo y restauración

**Comment by lupomontero** [comment]
De este _issue madre_ solo nos faltó completar el proyecto de _ecommerce_. Dado que el programa de extensión ya terminó, me tomo la libertad de cerrar este issue. Queda abierto el issue de _ecommerce_ (#1054) aunque en este momento pasa a estar etiquetado como _on hold_ para dar prioridad a `v4.x`.
